# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS

pod 'Moya'
pod 'Alamofire', '~> 5.4.4'
pod 'SwiftyJSON'
pod 'NSHash'
pod 'YYKit'

end
